---
name: ProfanityBlockPro
main: nsnguyenvuong\profanityblock\Loader
src-namespace-prefix: nsnguyenvuong\profanityblock
version: 0.0.1
api: [ 4.0.0 ]
author: NSNguyenVuong
description: Block all profanity from players
...
